// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWfEJ9_rBGC8F8gKOdmPVNxeA8-sKDwgw',
    appId: '1:410414215930:web:4db6930d44de0b48830f43',
    messagingSenderId: '410414215930',
    projectId: 'shopapp-3302f',
    authDomain: 'shopapp-3302f.firebaseapp.com',
    storageBucket: 'shopapp-3302f.appspot.com',
    measurementId: 'G-86W95RKBS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKu28HO_fyB9LDpDk6MdDEwRwpzrAJ8cw',
    appId: '1:410414215930:android:3c426a459d7db623830f43',
    messagingSenderId: '410414215930',
    projectId: 'shopapp-3302f',
    storageBucket: 'shopapp-3302f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKJU53Wrb-plF22cYg26Utq0XU5jK-A-k',
    appId: '1:410414215930:ios:1cb1fc7c8e62296c830f43',
    messagingSenderId: '410414215930',
    projectId: 'shopapp-3302f',
    storageBucket: 'shopapp-3302f.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKJU53Wrb-plF22cYg26Utq0XU5jK-A-k',
    appId: '1:410414215930:ios:1cb1fc7c8e62296c830f43',
    messagingSenderId: '410414215930',
    projectId: 'shopapp-3302f',
    storageBucket: 'shopapp-3302f.appspot.com',
    iosBundleId: 'com.example.ecommerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWfEJ9_rBGC8F8gKOdmPVNxeA8-sKDwgw',
    appId: '1:410414215930:web:0d71a168670cbe84830f43',
    messagingSenderId: '410414215930',
    projectId: 'shopapp-3302f',
    authDomain: 'shopapp-3302f.firebaseapp.com',
    storageBucket: 'shopapp-3302f.appspot.com',
    measurementId: 'G-SGLWR324K3',
  );
}
